version: 2
updates:
  - package-ecosystem: "npm" # Dependabot supports pnpm via the npm ecosystem config
    directory: "/" 
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
    labels:
      - "dependencies"
    groups:
      all-npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
    groups:
      all-actions:
        patterns:
          - "*"
