blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Gaetano-Taormina/KeyboardShortcut_Explorer/discussions
    about: Ask questions and discuss with the community
